[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
python = ">=3.7,<3.11"

[project]
version = "1.0.0"

[tool.poetry]
name = "beacon-omop-worker"
description = ''
readme = "README.md"
license = "MIT"
keywords = []
authors = [
  "Vasiliki Panagi <vasiliki.panagi@nottingham.ac.uk>"
]
version = "0.0.1"
package-mode = true
packages = [
    { include = "beacon_omop_worker" },
    { include = "scripts" },
]

[tool.poetry.dependencies]
sqlalchemy = "^2.0.29"
pandas=">=1.4.4"
psycopg2-binary = "^2.9.9"
requests="2.31.0"
python = ">=3.9,<3.11"

numpy = "<2.0"
poetry-dotenv-plugin = "^0.2.0"
lifelines = "^0.29.0"
[tool.poetry.group.dev.dependencies]
black = "^24.4.0"

[project.optional-dependencies]
mysql = [
  "mysqlclient~=2.1.1",
]
sqlserver = [
  "pyodbc~=4.0.35",
]

[tool.poetry.scripts]
beacon-omop-worker = "scripts.worker:main"
